/*
 * ProjectDatminView.java
 */
package projectdatmin;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class ProjectDatminView extends FrameView {

    static String transaksi1;
    static String transaksi2;
    static String transaksi3;
    static String transaksi4;
    static String transaksi5;
    static double minsuport;

    public ProjectDatminView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {

            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String) (evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer) (evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ProjectDatminApp.getApplication().getMainFrame();
            aboutBox = new Dataset(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ProjectDatminApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cetak3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cetak = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        minsup = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cetak2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        trans5 = new javax.swing.JTextField();
        trans2 = new javax.swing.JTextField();
        trans1 = new javax.swing.JTextField();
        trans4 = new javax.swing.JTextField();
        trans3 = new javax.swing.JTextField();
        progressBar = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        akhir = new javax.swing.JTextArea();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1358, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(projectdatmin.ProjectDatminApp.class).getContext().getResourceMap(ProjectDatminView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(resourceMap.getIcon("jMenuItem2.icon")); // NOI18N
        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem2);

        jMenuItem1.setIcon(resourceMap.getIcon("jMenuItem1.icon")); // NOI18N
        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(projectdatmin.ProjectDatminApp.class).getContext().getActionMap(ProjectDatminView.class, this);
        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setIcon(resourceMap.getIcon("aboutMenuItem.icon")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        jPanel3.setName("jPanel3"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        cetak3.setColumns(20);
        cetak3.setRows(5);
        cetak3.setName("cetak3"); // NOI18N
        jScrollPane3.setViewportView(cetak3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(165, 165, 165)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(144, 144, 144))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        cetak.setColumns(20);
        cetak.setRows(5);
        cetak.setName("cetak"); // NOI18N
        jScrollPane1.setViewportView(cetak);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        minsup.setText(resourceMap.getString("minsup.text")); // NOI18N
        minsup.setToolTipText(resourceMap.getString("minsup.toolTipText")); // NOI18N
        minsup.setName("minsup"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        jPanel2.setName("jPanel2"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        cetak2.setColumns(20);
        cetak2.setRows(5);
        cetak2.setName("cetak2"); // NOI18N
        jScrollPane2.setViewportView(cetak2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        trans5.setText(resourceMap.getString("trans5.text")); // NOI18N
        trans5.setToolTipText(resourceMap.getString("trans5.toolTipText")); // NOI18N
        trans5.setName("trans5"); // NOI18N

        trans2.setText(resourceMap.getString("trans5.text")); // NOI18N
        trans2.setName("trans2"); // NOI18N

        trans1.setText(resourceMap.getString("trans5.text")); // NOI18N
        trans1.setToolTipText(resourceMap.getString("trans1.toolTipText")); // NOI18N
        trans1.setName("trans1"); // NOI18N

        trans4.setText(resourceMap.getString("trans5.text")); // NOI18N
        trans4.setToolTipText(resourceMap.getString("trans4.toolTipText")); // NOI18N
        trans4.setName("trans4"); // NOI18N

        trans3.setText(resourceMap.getString("trans5.text")); // NOI18N
        trans3.setToolTipText(resourceMap.getString("trans3.toolTipText")); // NOI18N
        trans3.setName("trans3"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        akhir.setColumns(20);
        akhir.setRows(5);
        akhir.setName("akhir"); // NOI18N
        jScrollPane4.setViewportView(akhir);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(211, 211, 211))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(trans1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trans2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trans3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trans4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trans5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(538, 538, 538))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minsup, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(971, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trans1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trans2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trans3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trans4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trans5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minsup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))
                    .addGroup(statusPanelLayout.createSequentialGroup()
                        .addComponent(statusMessageLabel)
                        .addGap(1219, 1219, 1219)
                        .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                                .addComponent(statusAnimationLabel)
                                .addContainerGap())))))
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 979, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel))
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    minsuport = Double.parseDouble(minsup.getText());
    transaksi1 = trans1.getText();
    transaksi2 = trans2.getText();
    transaksi3 = trans3.getText();
    transaksi4 = trans4.getText();
    transaksi5 = trans5.getText();
    rumus rms = new rumus();
    rms.datmin();
    rms.proses1();
    rms.datmin1();
    rms.proses2();
    rms.datmin2();

    if (rms.jumlah1 > minsuport && rms.jumlah2 > minsuport && rms.jumlah11 >= minsuport) {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + ":" + rms.jumlah11 + "\n");
    } else {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + ":" + rms.jumlah11 + " dieliminasi \n");
    }
    if (rms.jumlah1 > minsuport && rms.jumlah3 > minsuport && rms.jumlah12 >= minsuport) {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari3 + ":" + rms.jumlah12 + "\n");
    } else {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari3 + ":" + rms.jumlah12 + " dieliminasi \n");
    }
    if (rms.jumlah1 > minsuport && rms.jumlah4 > minsuport && rms.jumlah13 >= minsuport) {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari4 + ":" + rms.jumlah13 + "\n");
    } else {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari4 + ":" + rms.jumlah13 + " dieliminasi \n");
    }
    if (rms.jumlah1 > minsuport && rms.jumlah5 > minsuport && rms.jumlah14 >= minsuport) {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari5 + ":" + rms.jumlah14 + "\n");
    } else {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari5 + ":" + rms.jumlah14 + " dieliminasi \n");
    }
    if (rms.jumlah2 > minsuport && rms.jumlah3 > minsuport && rms.jumlah15 >= minsuport) {
        cetak2.append(rms.kataygdicari2 + "," + rms.kataygdicari3 + ":" + rms.jumlah15 + "\n");
    } else {
        cetak2.append(rms.kataygdicari2 + "," + rms.kataygdicari3 + ":" + rms.jumlah15 + " dieliminasi \n");
    }
    if (rms.jumlah2 > minsuport && rms.jumlah4 > minsuport && rms.jumlah16 >= minsuport) {
        cetak2.append(rms.kataygdicari2 + "," + rms.kataygdicari4 + ":" + rms.jumlah16 + "\n");
    } else {
        cetak2.append(rms.kataygdicari2 + "," + rms.kataygdicari4 + ":" + rms.jumlah16 + " dieliminasi \n");
    }
    if (rms.jumlah2 > minsuport && rms.jumlah5 > minsuport && rms.jumlah17 >= minsuport) {
        cetak2.append(rms.kataygdicari2 + "," + rms.kataygdicari5 + ":" + rms.jumlah17 + "\n");
    } else {
        cetak2.append(rms.kataygdicari1 + "," + rms.kataygdicari4 + ":" + rms.jumlah17 + " dieliminasi \n");
    }
    if (rms.jumlah3 > minsuport && rms.jumlah4 > minsuport && rms.jumlah18 >= minsuport) {
        cetak2.append(rms.kataygdicari3 + "," + rms.kataygdicari4 + ":" + rms.jumlah18 + "\n");
    } else {
        cetak2.append(rms.kataygdicari3 + "," + rms.kataygdicari4 + ":" + rms.jumlah18 + " dieliminasi \n");
    }
    if (rms.jumlah3 > minsuport && rms.jumlah5 > minsuport && rms.jumlah19 >= minsuport) {
        cetak2.append(rms.kataygdicari3 + "," + rms.kataygdicari5 + ":" + rms.jumlah19 + "\n");
    } else {
        cetak2.append(rms.kataygdicari3 + "," + rms.kataygdicari5 + ":" + rms.jumlah19 + " dieliminasi \n");
    }
    if (rms.jumlah4 > minsuport && rms.jumlah5 > minsuport && rms.jumlah20 >= minsuport) {
        cetak2.append(rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah20 + "\n");
    } else {
        cetak2.append(rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah20 + " dieliminasi \n");
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    //Proses pertama

    minsuport = Double.parseDouble(minsup.getText());
    transaksi1 = trans1.getText();
    transaksi2 = trans2.getText();
    transaksi3 = trans3.getText();
    transaksi4 = trans4.getText();
    transaksi5 = trans5.getText();
    rumus rms = new rumus();
    rms.datmin();
    rms.proses1();
    rms.datmin1();
    rms.proses2();
    rms.datmin2();
    cetak.append(rms.kataygdicari1 + ":" + rms.jumlah1 + "\n");
    cetak.append(rms.kataygdicari2 + ":" + rms.jumlah2 + "\n");
    cetak.append(rms.kataygdicari3 + ":" + rms.jumlah3 + "\n");
    cetak.append(rms.kataygdicari4 + ":" + rms.jumlah4 + "\n");
    cetak.append(rms.kataygdicari5 + ":" + rms.jumlah5 + "\n");
    Math.max(rms.jumlah1, rms.jumlah2);
}//GEN-LAST:event_jButton1ActionPerformed

    @SuppressWarnings("static-access")
private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        minsuport = Double.parseDouble(minsup.getText());
        transaksi1 = trans1.getText();
        transaksi2 = trans2.getText();
        transaksi3 = trans3.getText();
        transaksi4 = trans4.getText();
        transaksi5 = trans5.getText();
        float jumlaha = 0;
        float jumlahb = 0;
        float jumlahc = 0;
        float jumlahd = 0;
        float jumlahe = 0;
        float jumlahf = 0;
        float jumlahall;

        rumus rms = new rumus();
        rms.datmin();
        rms.proses1();
        rms.datmin1();
        rms.proses2();
        rms.datmin2();


        if (rms.jumlah1 > minsuport && rms.jumlah2 > minsuport && rms.jumlah3 > minsuport && rms.jumlah21 >= minsuport) {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari3 + ":" + rms.jumlah21 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari3 + "\n");
            jumlaha = rms.jumlah1;
            jumlahb = rms.jumlah2;
            jumlahc = rms.jumlah3;
            jumlahd = rms.jumlah11;
            jumlahe = rms.jumlah12;
            jumlahf = rms.jumlah15;
            jumlahall = rms.jumlah21;
            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari2, rms.kataygdicari3, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari3 + ":" + rms.jumlah21 + "    dieliminasi \n");
        }
        if (rms.jumlah1 > minsuport && rms.jumlah2 > minsuport && rms.jumlah4 > minsuport && rms.jumlah22 >= minsuport) {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari4 + ":" + rms.jumlah22 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari4 + "\n");
            jumlaha = rms.jumlah1;
            jumlahb = rms.jumlah2;
            jumlahc = rms.jumlah4;
            jumlahd = rms.jumlah11;
            jumlahe = rms.jumlah13;
            jumlahf = rms.jumlah16;
            jumlahall = rms.jumlah22;
            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari2, rms.kataygdicari4, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari4 + ":" + rms.jumlah22 + " dieliminasi \n");
        }
        if (rms.jumlah1 > minsuport && rms.jumlah2 > minsuport && rms.jumlah5 > minsuport && rms.jumlah23 >= minsuport) {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari5 + ":" + rms.jumlah23 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari5+ "\n");
            jumlaha = rms.jumlah1;
            jumlahb = rms.jumlah2;
            jumlahc = rms.jumlah5;
            jumlahd = rms.jumlah11;
            jumlahe = rms.jumlah14;
            jumlahf = rms.jumlah17;
            jumlahall = rms.jumlah23;
            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari2, rms.kataygdicari5, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari2 + "," + rms.kataygdicari5 + ":" + rms.jumlah23 + " dieliminasi \n");
        }
        if (rms.jumlah1 > minsuport && rms.jumlah3 > minsuport && rms.jumlah4 > minsuport && rms.jumlah24 >= minsuport) {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari3 + "," + rms.kataygdicari4 + ":" + rms.jumlah24 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari1 + "," + rms.kataygdicari3 + "," + rms.kataygdicari4+ "\n");
            jumlaha = rms.jumlah1;
            jumlahb = rms.jumlah3;
            jumlahc = rms.jumlah4;
            jumlahd = rms.jumlah12;
            jumlahe = rms.jumlah13;
            jumlahf = rms.jumlah18;
            jumlahall = rms.jumlah24;
            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari3, rms.kataygdicari4, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari3 + "," + rms.kataygdicari4 + ":" + rms.jumlah24 + " dieliminasi \n");
        }
        if (rms.jumlah1 > minsuport && rms.jumlah3 > minsuport && rms.jumlah5 > minsuport && rms.jumlah25 >= minsuport) {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari3 + "," + rms.kataygdicari5 + ":" + rms.jumlah25 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari1 + "," + rms.kataygdicari3 + "," + rms.kataygdicari5+ "\n");
            jumlaha = rms.jumlah1;
            jumlahb = rms.jumlah2;
            jumlahc = rms.jumlah5;
            jumlahd = rms.jumlah12;
            jumlahe = rms.jumlah14;
            jumlahf = rms.jumlah19;
            jumlahall = rms.jumlah25;
            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari3, rms.kataygdicari5, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari3 + "," + rms.kataygdicari5 + ":" + rms.jumlah25 + " dieliminasi \n");
        }
        if (rms.jumlah2 > minsuport && rms.jumlah3 > minsuport && rms.jumlah4 > minsuport && rms.jumlah26 >= minsuport) {
            cetak3.append(rms.kataygdicari2 + "," + rms.kataygdicari3 + "," + rms.kataygdicari4 + ":" + rms.jumlah26 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari2 + "," + rms.kataygdicari3 + "," + rms.kataygdicari4+ "\n");
            jumlaha = rms.jumlah2;
            jumlahb = rms.jumlah3;
            jumlahc = rms.jumlah4;
            jumlahd = rms.jumlah15;
            jumlahe = rms.jumlah16;
            jumlahf = rms.jumlah18;
            jumlahall = rms.jumlah26;
            rms.fungsi3(rms.kataygdicari2, rms.kataygdicari3, rms.kataygdicari4, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari2 + "," + rms.kataygdicari3 + "," + rms.kataygdicari4 + ":" + rms.jumlah26 + " dieliminasi \n");
        }
        if (rms.jumlah2 > minsuport && rms.jumlah3 > minsuport && rms.jumlah5 > minsuport && rms.jumlah27 >= minsuport) {
            cetak3.append(rms.kataygdicari2 + "," + rms.kataygdicari3 + "," + rms.kataygdicari5 + ":" + rms.jumlah27 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari2 + "," + rms.kataygdicari3 + "," + rms.kataygdicari5+ "\n");
            jumlaha = rms.jumlah2;
            jumlahb = rms.jumlah3;
            jumlahc = rms.jumlah5;
            jumlahd = rms.jumlah15;
            jumlahe = rms.jumlah17;
            jumlahf = rms.jumlah19;
            jumlahall = rms.jumlah27;
            rms.fungsi3(rms.kataygdicari2, rms.kataygdicari3, rms.kataygdicari5, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);

        } else {
            cetak3.append(rms.kataygdicari2 + "," + rms.kataygdicari3 + "," + rms.kataygdicari5 + ":" + rms.jumlah27 + " dieliminasi \n");
        }
        if (rms.jumlah2 > minsuport && rms.jumlah4 > minsuport && rms.jumlah5 > minsuport && rms.jumlah28 >= minsuport) {
            cetak3.append(rms.kataygdicari2 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah28 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari2 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5+ "\n");
            jumlaha = rms.jumlah2;
            jumlahb = rms.jumlah4;
            jumlahc = rms.jumlah5;
            jumlahd = rms.jumlah16;
            jumlahe = rms.jumlah17;
            jumlahf = rms.jumlah20;
            jumlahall = rms.jumlah28;
            rms.fungsi3(rms.kataygdicari2, rms.kataygdicari4, rms.kataygdicari5, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);
        } else {
            cetak3.append(rms.kataygdicari2 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah28 + " dieliminasi \n");
        }
        if (rms.jumlah1 > minsuport && rms.jumlah4 > minsuport && rms.jumlah5 > minsuport && rms.jumlah30 >= minsuport) {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah30 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari1 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5+ "\n");
            jumlaha = rms.jumlah1;
            jumlahb = rms.jumlah4;
            jumlahc = rms.jumlah5;
            jumlahd = rms.jumlah13;
            jumlahe = rms.jumlah14;
            jumlahf = rms.jumlah20;
            jumlahall = rms.jumlah30;
            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari4, rms.kataygdicari5, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);


        } else {
            cetak3.append(rms.kataygdicari1 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah30 + " dieliminasi \n");
        }

        if (rms.jumlah3 > minsuport && rms.jumlah4 > minsuport && rms.jumlah5 > minsuport && rms.jumlah29 >= minsuport) {
            cetak3.append(rms.kataygdicari3 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah29 + "\n");
            akhir.setText("Hasil Akhir:" + rms.kataygdicari3 + "=>" + rms.kataygdicari4 + "," + rms.kataygdicari5+ "\n");
            jumlaha = rms.jumlah3;
            jumlahb = rms.jumlah4;
            jumlahc = rms.jumlah5;
            jumlahd = rms.jumlah18;
            jumlahe = rms.jumlah19;
            jumlahf = rms.jumlah20;
            jumlahall = rms.jumlah30;

            rms.fungsi3(rms.kataygdicari1, rms.kataygdicari4, rms.kataygdicari5, jumlaha, jumlahb, jumlahc, jumlahd, jumlahe, jumlahf, jumlahall);


        } else {
            cetak3.append(rms.kataygdicari3 + "," + rms.kataygdicari4 + "," + rms.kataygdicari5 + ":" + rms.jumlah29 + " dieliminasi \n");
        }
        
        akhir.append("Penjabaran Aturan dari Hasil Akhir \n");
        akhir.append(rms.hslkata1 + "=>" + rms.hslkata2 + "," + rms.hslkata3 + "    dengan jumlah support : " + rms.s1 + "   dan  jumlah confidence : " + rms.c1 + "\n");
        akhir.append(rms.hslkata2 + "=>" + rms.hslkata1 + "," + rms.hslkata3 + "    dengan jumlah support : " + rms.s1 + "   dan  jumlah confidence : " + rms.c2 + "\n");
        akhir.append(rms.hslkata3 + "=>" + rms.hslkata1 + "," + rms.hslkata2 + "    dengan jumlah support : " + rms.s1 + "   dan  jumlah confidence : " + rms.c3 + "\n");
        akhir.append(rms.hslkata1 + "," + rms.hslkata2 + "=>" + rms.hslkata3 + "    dengan jumlah support : " + rms.s1 + "   dan  jumlah confidence : " + rms.c4 + "\n");
        akhir.append(rms.hslkata1 + "," + rms.hslkata3 + "=>" + rms.hslkata2 + "    dengan jumlah support : " + rms.s1 + "   dan  jumlah confidence : " + rms.c5 + "\n");
        akhir.append(rms.hslkata2 + "," + rms.hslkata3 + "=>" + rms.hslkata1 + "    dengan jumlah support : " + rms.s1 + "   dan  jumlah confidence : " + rms.c6 + "\n");

}//GEN-LAST:event_jButton3ActionPerformed

private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
// TODO add your handling code here:
    System.exit(busyIconIndex);
}//GEN-LAST:event_fileMenuActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
    JOptionPane.showMessageDialog(mainPanel, " Kelompk 1 APLIKASI PENENTUAN PENEMPATAN BUKU BERDASARKAN KATEGORI PADA PERPUSTAKAAN DENGAN METODE APRIORI \n"
            + " Nama Kelompok  : \n "
            + "M.Zatiar Erwan Kalam     105060807111062\n"
            + " Rr Octanty M             105060800111035\n"
            + " M.Hilman Fatah          105060807111093\n"
            + " Sriningsih	        105060813111002\n"
            + " Anastasia Chandra U     105060801111073\n");
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea akhir;
    private javax.swing.JTextArea cetak;
    private javax.swing.JTextArea cetak2;
    private javax.swing.JTextArea cetak3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField minsup;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JTextField trans1;
    private javax.swing.JTextField trans2;
    private javax.swing.JTextField trans3;
    private javax.swing.JTextField trans4;
    private javax.swing.JTextField trans5;
    // End of variables declaration//GEN-END:variables
    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;
    private JDialog aboutBox;
}
